# Build the service binary
build:
	go build -o bin/job-posting-service ./cmd/server

# Run the service locally
run:
	go run ./cmd/server

# Run tests
test:
	go test ./...

# Format code
fmt:
	go fmt ./...

# Tidy dependencies
tidy:
	go mod tidy
